-- Create Database Denormalization
USE [master]
GO

/****** Object:  Database [Denormalization]    Script Date: 12/2/2025 10:40:45 AM ******/
CREATE DATABASE [Denormalization]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Denormalization', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Denormalization.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Denormalization_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Denormalization_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Denormalization].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Denormalization] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Denormalization] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Denormalization] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Denormalization] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Denormalization] SET ARITHABORT OFF 
GO

ALTER DATABASE [Denormalization] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Denormalization] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Denormalization] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Denormalization] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Denormalization] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Denormalization] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Denormalization] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Denormalization] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Denormalization] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Denormalization] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Denormalization] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Denormalization] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Denormalization] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Denormalization] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Denormalization] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Denormalization] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Denormalization] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Denormalization] SET RECOVERY FULL 
GO

ALTER DATABASE [Denormalization] SET  MULTI_USER 
GO

ALTER DATABASE [Denormalization] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Denormalization] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Denormalization] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Denormalization] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Denormalization] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Denormalization] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Denormalization] SET QUERY_STORE = ON
GO

ALTER DATABASE [Denormalization] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Denormalization] SET  READ_WRITE 
GO



